"""
Script to send an OTP to the customer
"""

# pip install twilio
from twilio.rest import Client  # API Client which sends the sms

# To use environment variables
import os


def sendSMS(otp, number):
    sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']

    client = Client(sid, auth_token)
    # Creating the twilio client object

    client.messages.create(body=f"\nYour OTP is: {otp}\n"
                                f"Please do not share with anyone",
                           from_="+12565790887",
                           to=f"+91{number}"
                           )
    # Sending the message

    # Body is the content of the message. A text is prepended stating that we are using the free version of twilio.
    # This can be removed by buying the full version

    # from_ specifies the number which was generated by the twilio website for our account.
    # We are not receiving messages from this number as we are using the free trial version of the api

    # to specifies the number to which the message is to be sent
